[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"